export const comunasConvecta = [{
    "idBorough": 272,
    "name": "Aisén",
    "idRegion": 11
}, {
    "idBorough": 44,
    "name": "Algarrobo",
    "idRegion": 5
}, {
    "idBorough": 301,
    "name": "Alhué",
    "idRegion": 13
}, {
    "idBorough": 28,
    "name": "Alto del Carmen",
    "idRegion": 3
}, {
    "idBorough": 343,
    "name": "Alto Hospicio",
    "idRegion": 1
}, {
    "idBorough": 256,
    "name": "Ancud",
    "idRegion": 10
}, {
    "idBorough": 33,
    "name": "Andacollo",
    "idRegion": 4
}, {
    "idBorough": 197,
    "name": "Angol",
    "idRegion": 9
}, {
    "idBorough": 290,
    "name": "Antártica",
    "idRegion": 12
}, {
    "idBorough": 18,
    "name": "Antofagasta",
    "idRegion": 2
}, {
    "idBorough": 179,
    "name": "Antuco",
    "idRegion": 8
}, {
    "idBorough": 145,
    "name": "Arauco",
    "idRegion": 8
}, {
    "idBorough": 3,
    "name": "Arica",
    "idRegion": 15
}, {
    "idBorough": 309,
    "name": "Buín",
    "idRegion": 13
}, {
    "idBorough": 167,
    "name": "Bulnes",
    "idRegion": 8
}, {
    "idBorough": 53,
    "name": "Cabildo",
    "idRegion": 5
}, {
    "idBorough": 289,
    "name": "Cabo de Hornos",
    "idRegion": 12
}, {
    "idBorough": 175,
    "name": "Cabrero",
    "idRegion": 8
}, {
    "idBorough": 13,
    "name": "Calama",
    "idRegion": 2
}, {
    "idBorough": 255,
    "name": "Calbuco",
    "idRegion": 10
}, {
    "idBorough": 22,
    "name": "Caldera",
    "idRegion": 3
}, {
    "idBorough": 63,
    "name": "Calera",
    "idRegion": 5
}, {
    "idBorough": 307,
    "name": "Calera de Tango",
    "idRegion": 13
}, {
    "idBorough": 71,
    "name": "Calle Larga",
    "idRegion": 5
}, {
    "idBorough": 4,
    "name": "Camarones",
    "idRegion": 15
}, {
    "idBorough": 6,
    "name": "Camiña",
    "idRegion": 1
}, {
    "idBorough": 40,
    "name": "Canela",
    "idRegion": 4
}, {
    "idBorough": 149,
    "name": "Cañete",
    "idRegion": 8
}, {
    "idBorough": 210,
    "name": "Carahue",
    "idRegion": 9
}, {
    "idBorough": 47,
    "name": "Cartagena",
    "idRegion": 5
}, {
    "idBorough": 80,
    "name": "Casablanca",
    "idRegion": 5
}, {
    "idBorough": 259,
    "name": "Castro",
    "idRegion": 10
}, {
    "idBorough": 57,
    "name": "Catemu",
    "idRegion": 5
}, {
    "idBorough": 133,
    "name": "Cauquenes",
    "idRegion": 7
}, {
    "idBorough": 321,
    "name": "Cerrillos",
    "idRegion": 13
}, {
    "idBorough": 318,
    "name": "Cerro Navia",
    "idRegion": 13
}, {
    "idBorough": 267,
    "name": "Chaitén",
    "idRegion": 10
}, {
    "idBorough": 20,
    "name": "Chañaral",
    "idRegion": 3
}, {
    "idBorough": 132,
    "name": "Chanco",
    "idRegion": 7
}, {
    "idBorough": 113,
    "name": "Chépica",
    "idRegion": 6
}, {
    "idBorough": 196,
    "name": "Chiguayante",
    "idRegion": 8
}, {
    "idBorough": 276,
    "name": "Chile Chico",
    "idRegion": 11
}, {
    "idBorough": 161,
    "name": "Chillán",
    "idRegion": 8
}, {
    "idBorough": 172,
    "name": "Chillán Viejo",
    "idRegion": 8
}, {
    "idBorough": 114,
    "name": "Chimbarongo",
    "idRegion": 6
}, {
    "idBorough": 725,
    "name": "Chol Chol",
    "idRegion": 9
}, {
    "idBorough": 262,
    "name": "Chonchi",
    "idRegion": 10
}, {
    "idBorough": 271,
    "name": "Cisnes",
    "idRegion": 11
}, {
    "idBorough": 152,
    "name": "Cobquecura",
    "idRegion": 8
}, {
    "idBorough": 253,
    "name": "Cochamo",
    "idRegion": 10
}, {
    "idBorough": 277,
    "name": "Cochrane",
    "idRegion": 11
}, {
    "idBorough": 84,
    "name": "Codegua",
    "idRegion": 6
}, {
    "idBorough": 163,
    "name": "Coelemu",
    "idRegion": 8
}, {
    "idBorough": 274,
    "name": "Coihaique",
    "idRegion": 11
}, {
    "idBorough": 162,
    "name": "Coihueco",
    "idRegion": 8
}, {
    "idBorough": 91,
    "name": "Coinco",
    "idRegion": 6
}, {
    "idBorough": 118,
    "name": "Colbún",
    "idRegion": 7
}, {
    "idBorough": 7,
    "name": "Colchane",
    "idRegion": 1
}, {
    "idBorough": 292,
    "name": "Colina",
    "idRegion": 13
}, {
    "idBorough": 199,
    "name": "Collipulli",
    "idRegion": 9
}, {
    "idBorough": 88,
    "name": "Coltauco",
    "idRegion": 6
}, {
    "idBorough": 39,
    "name": "Combarbalá",
    "idRegion": 4
}, {
    "idBorough": 190,
    "name": "Concepción",
    "idRegion": 8
}, {
    "idBorough": 326,
    "name": "Conchalí",
    "idRegion": 13
}, {
    "idBorough": 81,
    "name": "Concón",
    "idRegion": 5
}, {
    "idBorough": 137,
    "name": "Constitución",
    "idRegion": 7
}, {
    "idBorough": 150,
    "name": "Contulmo",
    "idRegion": 8
}, {
    "idBorough": 23,
    "name": "Copiapó",
    "idRegion": 3
}, {
    "idBorough": 32,
    "name": "Coquimbo",
    "idRegion": 4
}, {
    "idBorough": 191,
    "name": "Coronel",
    "idRegion": 8
}, {
    "idBorough": 234,
    "name": "Corral",
    "idRegion": 14
}, {
    "idBorough": 219,
    "name": "Cunco",
    "idRegion": 9
}, {
    "idBorough": 207,
    "name": "Curacautín",
    "idRegion": 9
}, {
    "idBorough": 297,
    "name": "Curacaví",
    "idRegion": 13
}, {
    "idBorough": 260,
    "name": "Curaco de Vélez",
    "idRegion": 10
}, {
    "idBorough": 146,
    "name": "Curanilahue",
    "idRegion": 8
}, {
    "idBorough": 226,
    "name": "Curarrehue",
    "idRegion": 9
}, {
    "idBorough": 135,
    "name": "Curepto",
    "idRegion": 7
}, {
    "idBorough": 127,
    "name": "Curicó",
    "idRegion": 7
}, {
    "idBorough": 258,
    "name": "Dalcahue",
    "idRegion": 10
}, {
    "idBorough": 21,
    "name": "Diego de Almagro",
    "idRegion": 3
}, {
    "idBorough": 89,
    "name": "Doñihue",
    "idRegion": 6
}, {
    "idBorough": 333,
    "name": "El Bosque",
    "idRegion": 13
}, {
    "idBorough": 169,
    "name": "El Carmen",
    "idRegion": 8
}, {
    "idBorough": 303,
    "name": "El Monte",
    "idRegion": 13
}, {
    "idBorough": 45,
    "name": "El Quisco",
    "idRegion": 5
}, {
    "idBorough": 46,
    "name": "El Tabo",
    "idRegion": 5
}, {
    "idBorough": 143,
    "name": "Empedrado",
    "idRegion": 7
}, {
    "idBorough": 202,
    "name": "Ercilla",
    "idRegion": 9
}, {
    "idBorough": 338,
    "name": "Estación Central",
    "idRegion": 13
}, {
    "idBorough": 189,
    "name": "Florida",
    "idRegion": 8
}, {
    "idBorough": 218,
    "name": "Freire",
    "idRegion": 9
}, {
    "idBorough": 27,
    "name": "Freirina",
    "idRegion": 3
}, {
    "idBorough": 247,
    "name": "Fresia",
    "idRegion": 10
}, {
    "idBorough": 248,
    "name": "Frutillar",
    "idRegion": 10
}, {
    "idBorough": 268,
    "name": "Futalefu",
    "idRegion": 10
}, {
    "idBorough": 236,
    "name": "Futrono",
    "idRegion": 14
}, {
    "idBorough": 208,
    "name": "Galvarino",
    "idRegion": 9
}, {
    "idBorough": 1,
    "name": "General Lagos",
    "idRegion": 15
}, {
    "idBorough": 222,
    "name": "Gorbea",
    "idRegion": 9
}, {
    "idBorough": 83,
    "name": "Graneros",
    "idRegion": 6
}, {
    "idBorough": 270,
    "name": "Guaitecas",
    "idRegion": 11
}, {
    "idBorough": 66,
    "name": "Hijuelas",
    "idRegion": 5
}, {
    "idBorough": 266,
    "name": "Hualaihue",
    "idRegion": 10
}, {
    "idBorough": 125,
    "name": "Hualañe",
    "idRegion": 7
}, {
    "idBorough": 192,
    "name": "Hualqui",
    "idRegion": 8
}, {
    "idBorough": 5,
    "name": "Huara",
    "idRegion": 1
}, {
    "idBorough": 25,
    "name": "Huasco",
    "idRegion": 3
}, {
    "idBorough": 327,
    "name": "Huechuraba",
    "idRegion": 13
}, {
    "idBorough": 41,
    "name": "Illapel",
    "idRegion": 4
}, {
    "idBorough": 324,
    "name": "Independencia",
    "idRegion": 13
}, {
    "idBorough": 8,
    "name": "Iquique",
    "idRegion": 1
}, {
    "idBorough": 305,
    "name": "Isla de Maipo",
    "idRegion": 13
}, {
    "idBorough": 50,
    "name": "Isla de Pascua",
    "idRegion": 5
}, {
    "idBorough": 74,
    "name": "Juan Fernández",
    "idRegion": 5
}, {
    "idBorough": 330,
    "name": "La Cisterna",
    "idRegion": 13
}, {
    "idBorough": 64,
    "name": "La Cruz",
    "idRegion": 5
}, {
    "idBorough": 101,
    "name": "La Estrella",
    "idRegion": 6
}, {
    "idBorough": 316,
    "name": "La Florida",
    "idRegion": 13
}, {
    "idBorough": 332,
    "name": "La Granja",
    "idRegion": 13
}, {
    "idBorough": 29,
    "name": "La Higuera",
    "idRegion": 4
}, {
    "idBorough": 52,
    "name": "La Ligua",
    "idRegion": 5
}, {
    "idBorough": 334,
    "name": "La Pintana",
    "idRegion": 13
}, {
    "idBorough": 314,
    "name": "La Reina",
    "idRegion": 13
}, {
    "idBorough": 31,
    "name": "La Serena",
    "idRegion": 4
}, {
    "idBorough": 237,
    "name": "La Unión",
    "idRegion": 14
}, {
    "idBorough": 238,
    "name": "Lago Ranco",
    "idRegion": 14
}, {
    "idBorough": 273,
    "name": "Lago Verde",
    "idRegion": 11
}, {
    "idBorough": 282,
    "name": "Laguna Blanca",
    "idRegion": 12
}, {
    "idBorough": 176,
    "name": "Laja",
    "idRegion": 8
}, {
    "idBorough": 293,
    "name": "Lampa",
    "idRegion": 13
}, {
    "idBorough": 229,
    "name": "Lanco",
    "idRegion": 14
}, {
    "idBorough": 87,
    "name": "Las Cabras",
    "idRegion": 6
}, {
    "idBorough": 313,
    "name": "Las Condes",
    "idRegion": 13
}, {
    "idBorough": 213,
    "name": "Lautaro",
    "idRegion": 9
}, {
    "idBorough": 147,
    "name": "Lebu",
    "idRegion": 8
}, {
    "idBorough": 129,
    "name": "Licantén",
    "idRegion": 7
}, {
    "idBorough": 67,
    "name": "Limache",
    "idRegion": 5
}, {
    "idBorough": 119,
    "name": "Linares",
    "idRegion": 7
}, {
    "idBorough": 100,
    "name": "Litueche",
    "idRegion": 6
}, {
    "idBorough": 61,
    "name": "Llaillay",
    "idRegion": 5
}, {
    "idBorough": 250,
    "name": "Llanquihue",
    "idRegion": 10
}, {
    "idBorough": 311,
    "name": "Lo Barnechea",
    "idRegion": 13
}, {
    "idBorough": 328,
    "name": "Lo Espejo",
    "idRegion": 13
}, {
    "idBorough": 319,
    "name": "Lo Prado",
    "idRegion": 13
}, {
    "idBorough": 112,
    "name": "Lolol",
    "idRegion": 6
}, {
    "idBorough": 223,
    "name": "Loncoche",
    "idRegion": 9
}, {
    "idBorough": 121,
    "name": "Longaví",
    "idRegion": 7
}, {
    "idBorough": 203,
    "name": "Lonquimay",
    "idRegion": 9
}, {
    "idBorough": 148,
    "name": "Los Alamos",
    "idRegion": 8
}, {
    "idBorough": 72,
    "name": "Los Andes",
    "idRegion": 5
}, {
    "idBorough": 177,
    "name": "Los Angeles",
    "idRegion": 8
}, {
    "idBorough": 233,
    "name": "Los Lagos",
    "idRegion": 14
}, {
    "idBorough": 251,
    "name": "Los Muermos",
    "idRegion": 10
}, {
    "idBorough": 201,
    "name": "Los Sauces",
    "idRegion": 9
}, {
    "idBorough": 42,
    "name": "Los Vilos",
    "idRegion": 4
}, {
    "idBorough": 193,
    "name": "Lota",
    "idRegion": 8
}, {
    "idBorough": 204,
    "name": "Lumaco",
    "idRegion": 9
}, {
    "idBorough": 86,
    "name": "Machalí",
    "idRegion": 6
}, {
    "idBorough": 342,
    "name": "Macul",
    "idRegion": 13
}, {
    "idBorough": 231,
    "name": "Mafil",
    "idRegion": 14
}, {
    "idBorough": 320,
    "name": "Maipú",
    "idRegion": 13
}, {
    "idBorough": 97,
    "name": "Malloa",
    "idRegion": 6
}, {
    "idBorough": 103,
    "name": "Marchigüe",
    "idRegion": 6
}, {
    "idBorough": 12,
    "name": "María Elena",
    "idRegion": 2
}, {
    "idBorough": 298,
    "name": "María Pinto",
    "idRegion": 13
}, {
    "idBorough": 228,
    "name": "Mariquina",
    "idRegion": 14
}, {
    "idBorough": 142,
    "name": "Maule",
    "idRegion": 7
}, {
    "idBorough": 254,
    "name": "Maullín",
    "idRegion": 10
}, {
    "idBorough": 16,
    "name": "Mejillones",
    "idRegion": 2
}, {
    "idBorough": 215,
    "name": "Melipeuco",
    "idRegion": 9
}, {
    "idBorough": 299,
    "name": "Melipilla",
    "idRegion": 13
}, {
    "idBorough": 131,
    "name": "Molina",
    "idRegion": 7
}, {
    "idBorough": 38,
    "name": "Monte Patria",
    "idRegion": 4
}, {
    "idBorough": 82,
    "name": "Mostazal",
    "idRegion": 6
}, {
    "idBorough": 183,
    "name": "Mulchén",
    "idRegion": 8
}, {
    "idBorough": 181,
    "name": "Nacimiento",
    "idRegion": 8
}, {
    "idBorough": 110,
    "name": "Nancagua",
    "idRegion": 6
}, {
    "idBorough": 280,
    "name": "Natales",
    "idRegion": 12
}, {
    "idBorough": 99,
    "name": "Navidad",
    "idRegion": 6
}, {
    "idBorough": 182,
    "name": "Negrete",
    "idRegion": 8
}, {
    "idBorough": 154,
    "name": "Ninhue",
    "idRegion": 8
}, {
    "idBorough": 156,
    "name": "Ñiquén",
    "idRegion": 8
}, {
    "idBorough": 0,
    "name": "No Definida",
    "idRegion": 0
}, {
    "idBorough": 62,
    "name": "Nogales",
    "idRegion": 5
}, {
    "idBorough": 211,
    "name": "Nueva Imperial",
    "idRegion": 9
}, {
    "idBorough": 340,
    "name": "Ñuñoa",
    "idRegion": 13
}, {
    "idBorough": 279,
    "name": "O`Higgins",
    "idRegion": 11
}, {
    "idBorough": 90,
    "name": "Olivar",
    "idRegion": 6
}, {
    "idBorough": 14,
    "name": "Ollagüe",
    "idRegion": 2
}, {
    "idBorough": 68,
    "name": "Olmué",
    "idRegion": 5
}, {
    "idBorough": 242,
    "name": "Osorno",
    "idRegion": 10
}, {
    "idBorough": 35,
    "name": "Ovalle",
    "idRegion": 4
}, {
    "idBorough": 306,
    "name": "Padre Hurtado",
    "idRegion": 13
}, {
    "idBorough": 227,
    "name": "Padre las Casas",
    "idRegion": 9
}, {
    "idBorough": 34,
    "name": "Paiguano",
    "idRegion": 4
}, {
    "idBorough": 235,
    "name": "Paillaco",
    "idRegion": 14
}, {
    "idBorough": 310,
    "name": "Paine",
    "idRegion": 13
}, {
    "idBorough": 269,
    "name": "Palena",
    "idRegion": 10
}, {
    "idBorough": 106,
    "name": "Palmilla",
    "idRegion": 6
}, {
    "idBorough": 230,
    "name": "Panguipulli",
    "idRegion": 14
}, {
    "idBorough": 60,
    "name": "Panquehue",
    "idRegion": 5
}, {
    "idBorough": 54,
    "name": "Papudo",
    "idRegion": 5
}, {
    "idBorough": 104,
    "name": "Paredones",
    "idRegion": 6
}, {
    "idBorough": 122,
    "name": "Parral",
    "idRegion": 7
}, {
    "idBorough": 329,
    "name": "Pedro Aguirre Cerda",
    "idRegion": 13
}, {
    "idBorough": 140,
    "name": "Pelarco",
    "idRegion": 7
}, {
    "idBorough": 134,
    "name": "Pelluhue",
    "idRegion": 7
}, {
    "idBorough": 170,
    "name": "Pemuco",
    "idRegion": 8
}, {
    "idBorough": 302,
    "name": "Peñaflor",
    "idRegion": 13
}, {
    "idBorough": 315,
    "name": "Peñalolén",
    "idRegion": 13
}, {
    "idBorough": 138,
    "name": "Pencahue",
    "idRegion": 7
}, {
    "idBorough": 188,
    "name": "Penco",
    "idRegion": 8
}, {
    "idBorough": 105,
    "name": "Peralillo",
    "idRegion": 6
}, {
    "idBorough": 209,
    "name": "Perquenco",
    "idRegion": 9
}, {
    "idBorough": 51,
    "name": "Petorca",
    "idRegion": 5
}, {
    "idBorough": 93,
    "name": "Peumo",
    "idRegion": 6
}, {
    "idBorough": 10,
    "name": "Pica",
    "idRegion": 1
}, {
    "idBorough": 95,
    "name": "Pichidegua",
    "idRegion": 6
}, {
    "idBorough": 102,
    "name": "Pichilemu",
    "idRegion": 6
}, {
    "idBorough": 165,
    "name": "Pinto",
    "idRegion": 8
}, {
    "idBorough": 296,
    "name": "Pirque",
    "idRegion": 13
}, {
    "idBorough": 221,
    "name": "Pitrufquén",
    "idRegion": 9
}, {
    "idBorough": 111,
    "name": "Placilla",
    "idRegion": 6
}, {
    "idBorough": 160,
    "name": "Portezuelo",
    "idRegion": 8
}, {
    "idBorough": 287,
    "name": "Porvenir",
    "idRegion": 12
}, {
    "idBorough": 9,
    "name": "Pozo Almonte",
    "idRegion": 1
}, {
    "idBorough": 286,
    "name": "Primavera",
    "idRegion": 12
}, {
    "idBorough": 337,
    "name": "Providencia",
    "idRegion": 13
}, {
    "idBorough": 73,
    "name": "Puchuncaví",
    "idRegion": 5
}, {
    "idBorough": 225,
    "name": "Pucón",
    "idRegion": 9
}, {
    "idBorough": 317,
    "name": "Pudahuel",
    "idRegion": 13
}, {
    "idBorough": 295,
    "name": "Puente Alto",
    "idRegion": 13
}, {
    "idBorough": 252,
    "name": "Puerto Montt",
    "idRegion": 10
}, {
    "idBorough": 245,
    "name": "Puerto Octay",
    "idRegion": 10
}, {
    "idBorough": 249,
    "name": "Puerto Varas",
    "idRegion": 10
}, {
    "idBorough": 108,
    "name": "Pumanque",
    "idRegion": 6
}, {
    "idBorough": 37,
    "name": "Punitaqui",
    "idRegion": 4
}, {
    "idBorough": 285,
    "name": "Punta Arenas",
    "idRegion": 12
}, {
    "idBorough": 263,
    "name": "Puqueldón",
    "idRegion": 10
}, {
    "idBorough": 200,
    "name": "Purén",
    "idRegion": 9
}, {
    "idBorough": 246,
    "name": "Purranque",
    "idRegion": 10
}, {
    "idBorough": 56,
    "name": "Putaendo",
    "idRegion": 5
}, {
    "idBorough": 2,
    "name": "Putre",
    "idRegion": 15
}, {
    "idBorough": 243,
    "name": "Puyehue",
    "idRegion": 10
}, {
    "idBorough": 264,
    "name": "Queilén",
    "idRegion": 10
}, {
    "idBorough": 265,
    "name": "Quellón",
    "idRegion": 10
}, {
    "idBorough": 257,
    "name": "Quemchi",
    "idRegion": 10
}, {
    "idBorough": 185,
    "name": "Quilaco",
    "idRegion": 8
}, {
    "idBorough": 323,
    "name": "Quilicura",
    "idRegion": 13
}, {
    "idBorough": 180,
    "name": "Quilleco",
    "idRegion": 8
}, {
    "idBorough": 166,
    "name": "Quillón",
    "idRegion": 8
}, {
    "idBorough": 65,
    "name": "Quillota",
    "idRegion": 5
}, {
    "idBorough": 79,
    "name": "Quilpué",
    "idRegion": 5
}, {
    "idBorough": 261,
    "name": "Quinchao",
    "idRegion": 10
}, {
    "idBorough": 94,
    "name": "Quinta de Tilcoco",
    "idRegion": 6
}, {
    "idBorough": 336,
    "name": "Quinta Normal",
    "idRegion": 13
}, {
    "idBorough": 75,
    "name": "Quintero",
    "idRegion": 5
}, {
    "idBorough": 153,
    "name": "Quirihue",
    "idRegion": 8
}, {
    "idBorough": 85,
    "name": "Rancagua",
    "idRegion": 6
}, {
    "idBorough": 164,
    "name": "Ranquil",
    "idRegion": 8
}, {
    "idBorough": 126,
    "name": "Rauco",
    "idRegion": 7
}, {
    "idBorough": 325,
    "name": "Recoleta",
    "idRegion": 13
}, {
    "idBorough": 198,
    "name": "Renaico",
    "idRegion": 9
}, {
    "idBorough": 322,
    "name": "Renca",
    "idRegion": 13
}, {
    "idBorough": 98,
    "name": "Rengo",
    "idRegion": 6
}, {
    "idBorough": 92,
    "name": "Requínoa",
    "idRegion": 6
}, {
    "idBorough": 120,
    "name": "Retiro",
    "idRegion": 7
}, {
    "idBorough": 70,
    "name": "Rinconada",
    "idRegion": 5
}, {
    "idBorough": 239,
    "name": "Río Bueno",
    "idRegion": 14
}, {
    "idBorough": 136,
    "name": "Río Claro",
    "idRegion": 7
}, {
    "idBorough": 36,
    "name": "Río Hurtado",
    "idRegion": 4
}, {
    "idBorough": 275,
    "name": "Río Ibáñez",
    "idRegion": 11
}, {
    "idBorough": 244,
    "name": "Río Negro",
    "idRegion": 10
}, {
    "idBorough": 284,
    "name": "Río Verde",
    "idRegion": 12
}, {
    "idBorough": 128,
    "name": "Romeral",
    "idRegion": 7
}, {
    "idBorough": 216,
    "name": "Saavedra",
    "idRegion": 9
}, {
    "idBorough": 130,
    "name": "Sagrada Familia",
    "idRegion": 7
}, {
    "idBorough": 43,
    "name": "Salamanca",
    "idRegion": 4
}, {
    "idBorough": 48,
    "name": "San Antonio",
    "idRegion": 5
}, {
    "idBorough": 308,
    "name": "San Bernardo",
    "idRegion": 13
}, {
    "idBorough": 155,
    "name": "San Carlos",
    "idRegion": 8
}, {
    "idBorough": 141,
    "name": "San Clemente",
    "idRegion": 7
}, {
    "idBorough": 69,
    "name": "San Esteban",
    "idRegion": 5
}, {
    "idBorough": 157,
    "name": "San Fabián",
    "idRegion": 8
}, {
    "idBorough": 58,
    "name": "San Felipe",
    "idRegion": 5
}, {
    "idBorough": 107,
    "name": "San Fernando",
    "idRegion": 6
}, {
    "idBorough": 283,
    "name": "San Gregorio",
    "idRegion": 12
}, {
    "idBorough": 168,
    "name": "San Ignacio",
    "idRegion": 8
}, {
    "idBorough": 115,
    "name": "San Javier",
    "idRegion": 7
}, {
    "idBorough": 341,
    "name": "San Joaquín",
    "idRegion": 13
}, {
    "idBorough": 294,
    "name": "San José de Maipo",
    "idRegion": 13
}, {
    "idBorough": 240,
    "name": "San Juan de la Costa",
    "idRegion": 10
}, {
    "idBorough": 335,
    "name": "San Miguel",
    "idRegion": 13
}, {
    "idBorough": 158,
    "name": "San Nicolás",
    "idRegion": 8
}, {
    "idBorough": 241,
    "name": "San Pablo",
    "idRegion": 10
}, {
    "idBorough": 300,
    "name": "San Pedro",
    "idRegion": 13
}, {
    "idBorough": 15,
    "name": "San Pedro de Atacama",
    "idRegion": 2
}, {
    "idBorough": 195,
    "name": "San Pedro de la Paz",
    "idRegion": 8
}, {
    "idBorough": 144,
    "name": "San Rafael",
    "idRegion": 7
}, {
    "idBorough": 331,
    "name": "San Ramón",
    "idRegion": 13
}, {
    "idBorough": 173,
    "name": "San Rosendo",
    "idRegion": 8
}, {
    "idBorough": 96,
    "name": "San Vicente",
    "idRegion": 6
}, {
    "idBorough": 184,
    "name": "Santa Bárbara",
    "idRegion": 8
}, {
    "idBorough": 109,
    "name": "Santa Cruz",
    "idRegion": 6
}, {
    "idBorough": 194,
    "name": "Santa Juana",
    "idRegion": 8
}, {
    "idBorough": 59,
    "name": "Santa María",
    "idRegion": 5
}, {
    "idBorough": 339,
    "name": "Santiago",
    "idRegion": 13
}, {
    "idBorough": 49,
    "name": "Santo Domingo",
    "idRegion": 5
}, {
    "idBorough": 17,
    "name": "Sierra Gorda",
    "idRegion": 2
}, {
    "idBorough": 304,
    "name": "Talagante",
    "idRegion": 13
}, {
    "idBorough": 139,
    "name": "Talca",
    "idRegion": 7
}, {
    "idBorough": 187,
    "name": "Talcahuano",
    "idRegion": 8
}, {
    "idBorough": 19,
    "name": "Taltal",
    "idRegion": 2
}, {
    "idBorough": 212,
    "name": "Temuco",
    "idRegion": 9
}, {
    "idBorough": 123,
    "name": "Teno",
    "idRegion": 7
}, {
    "idBorough": 217,
    "name": "Teodoro Schmidt",
    "idRegion": 9
}, {
    "idBorough": 24,
    "name": "Tierra Amarilla",
    "idRegion": 3
}, {
    "idBorough": 291,
    "name": "Tiltil",
    "idRegion": 13
}, {
    "idBorough": 288,
    "name": "Timaukel",
    "idRegion": 12
}, {
    "idBorough": 151,
    "name": "Tirúa",
    "idRegion": 8
}, {
    "idBorough": 11,
    "name": "Tocopilla",
    "idRegion": 2
}, {
    "idBorough": 220,
    "name": "Toltén",
    "idRegion": 9
}, {
    "idBorough": 186,
    "name": "Tomé",
    "idRegion": 8
}, {
    "idBorough": 281,
    "name": "Torres del Paine",
    "idRegion": 12
}, {
    "idBorough": 278,
    "name": "Tortel",
    "idRegion": 11
}, {
    "idBorough": 205,
    "name": "Traiguén",
    "idRegion": 9
}, {
    "idBorough": 159,
    "name": "Treguaco",
    "idRegion": 8
}, {
    "idBorough": 178,
    "name": "Tucapel",
    "idRegion": 8
}, {
    "idBorough": 232,
    "name": "Valdivia",
    "idRegion": 14
}, {
    "idBorough": 26,
    "name": "Vallenar",
    "idRegion": 3
}, {
    "idBorough": 78,
    "name": "Valparaíso",
    "idRegion": 5
}, {
    "idBorough": 124,
    "name": "Vichuquén",
    "idRegion": 7
}, {
    "idBorough": 206,
    "name": "Victoria",
    "idRegion": 9
}, {
    "idBorough": 30,
    "name": "Vicuña",
    "idRegion": 4
}, {
    "idBorough": 214,
    "name": "Vilcún",
    "idRegion": 9
}, {
    "idBorough": 116,
    "name": "Villa Alegre",
    "idRegion": 7
}, {
    "idBorough": 77,
    "name": "Villa Alemana",
    "idRegion": 5
}, {
    "idBorough": 224,
    "name": "Villarrica",
    "idRegion": 9
}, {
    "idBorough": 76,
    "name": "Viña del Mar",
    "idRegion": 5
}, {
    "idBorough": 312,
    "name": "Vitacura",
    "idRegion": 13
}, {
    "idBorough": 117,
    "name": "Yerbas Buenas",
    "idRegion": 7
}, {
    "idBorough": 174,
    "name": "Yumbel",
    "idRegion": 8
}, {
    "idBorough": 171,
    "name": "Yungay",
    "idRegion": 8
}, {
    "idBorough": 55,
    "name": "Zapallar",
    "idRegion": 5
}]

export const regionesConvecta = [{
    "idRegion": 13,
    "idCountry": 1,
    "name": "Metropolitana"
}, {
    "idRegion": 14,
    "idCountry": 1,
    "name": "Los Ríos"
}, {
    "idRegion": 15,
    "idCountry": 1,
    "name": "Arica y Parinacota"
}, {
    "idRegion": 0,
    "idCountry": 1,
    "name": "Ninguna"
}, {
    "idRegion": 1,
    "idCountry": 1,
    "name": "Tarapacá"
}, {
    "idRegion": 2,
    "idCountry": 1,
    "name": "Antofagasta"
}, {
    "idRegion": 3,
    "idCountry": 1,
    "name": "Atacama"
}, {
    "idRegion": 4,
    "idCountry": 1,
    "name": "Coquimbo"
}, {
    "idRegion": 5,
    "idCountry": 1,
    "name": "Valparaiso"
}, {
    "idRegion": 6,
    "idCountry": 1,
    "name": "Bernardo OHiggins"
}, {
    "idRegion": 7,
    "idCountry": 1,
    "name": "Maule"
}, {
    "idRegion": 8,
    "idCountry": 1,
    "name": "Bío-Bío"
}, {
    "idRegion": 9,
    "idCountry": 1,
    "name": "Araucanía"
}, {
    "idRegion": 10,
    "idCountry": 1,
    "name": "Los Lagos"
}, {
    "idRegion": 11,
    "idCountry": 1,
    "name": "Aysén"
}, {
    "idRegion": 12,
    "idCountry": 1,
    "name": "Magallanes y Antártica"
}]

export const usuariosConvecta = [{
    "idUser": 1272,
    "nombreCompleto": "Convecta Prop360",
    "email": "info@convecta.cl"
}, {
    "idUser": 1273,
    "nombreCompleto": "Paola Villarroel Leon",
    "email": "pvillarroel@1house.cl"
}, {
    "idUser": 1274,
    "nombreCompleto": "Ana Rosa Leon Diaz",
    "email": "aleon@1house.cl"
}, {
    "idUser": 1275,
    "nombreCompleto": "Carlos Vega",
    "email": "cvega@1house.cl"
}, {
    "idUser": 1276,
    "nombreCompleto": "Natalia Rodriguez",
    "email": "nrodriguez@1house.cl"
}, {
    "idUser": 1277,
    "nombreCompleto": "Henry Becerra Tine",
    "email": "hbecerra@1house.cl"
}, {
    "idUser": 1278,
    "nombreCompleto": "Basly Silva",
    "email": "bsilva@1house.cl"
}, {
    "idUser": 1279,
    "nombreCompleto": "Gigliola Vicencio",
    "email": "gvicencio@1house.cl"
}, {
    "idUser": 1280,
    "nombreCompleto": "Pablo Peralta Pavez",
    "email": "pperalta@1house.cl"
}, {
    "idUser": 1281,
    "nombreCompleto": "Alvaro Donoso Bravo",
    "email": "adonoso@1house.cl"
}, {
    "idUser": 1282,
    "nombreCompleto": "Yivana Yanez",
    "email": "yyanez@1house.cl"
}, {
    "idUser": 1283,
    "nombreCompleto": "Jessica Galvez",
    "email": "jgalvez@1house.cl"
}, {
    "idUser": 1284,
    "nombreCompleto": "Maciel Moreno Alarcon",
    "email": "mmoreno@1house.cl"
}, {
    "idUser": 1286,
    "nombreCompleto": "Victoria Araujo",
    "email": "coordinadora@1house.cl"
}, {
    "idUser": 1287,
    "nombreCompleto": "Lizeth Huerta",
    "email": "lhuerta@1house.cl"
}, {
    "idUser": 1288,
    "nombreCompleto": "Marcelo Fredericksen",
    "email": "mfredericksen@1house.cl"
}, {
    "idUser": 1289,
    "nombreCompleto": "Vannia Suarez",
    "email": "vsuarez@1house.cl"
}, {
    "idUser": 1290,
    "nombreCompleto": "Maria Jacqueline Valderas",
    "email": "mvalderas@1house.cl"
}, {
    "idUser": 1291,
    "nombreCompleto": "Oriana Quijada",
    "email": "oquijada@1house.cl"
}, {
    "idUser": 1292,
    "nombreCompleto": "Mary Carmen Angulo",
    "email": "mangulo@1house.cl"
}, {
    "idUser": 1293,
    "nombreCompleto": "Laila Kadadihi",
    "email": "lkadadihi@1house.cl"
}, {
    "idUser": 1294,
    "nombreCompleto": "Sergio Herrera",
    "email": "sherrera@1house.cl"
}]
