export const dataLenguage = {
    startsWith: "Comienza con",
    contains: "Contiene",
    notContains: "No contiene",
    endsWith: "Termina con",
    equals: "Igual a",
    notEquals: "Diferente de",
    noFilter: "Quitar filtro",
    matchAll: "Buscar todo",
    matchAny: "Buscar algo",
    dayNames: ["Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"],
    dayNamesShort: ["Dom", "Lun", "Mar", "Mir", "Jue", "Vie", "Sab"],
    dayNamesMin: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
    monthNames: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
    monthNamesShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
    dateFormat: "dd/mm/yy",
    emptyMessage: "No se encontraron resultados",
    emptyFilterMessage: "No se encontraron resultados",
    lt: "Menor que",
    lte: "Menor o igual que",
    gt: "Mayor que",
    gte: "Mayor o igual que",
    is: "Es",
    isNot: "No es",
    before: "Antes",
    after: "Despues",
    dateIs: "Fecha es",
    dateIsNot: "No Fecha",
    dateBefore: "Antes de la fecha",
    dateAfter: "Despues de la fecha",
    clear: "Limpiar",
    apply: "Aplicar",
    addRule: "Agregar otro filtro"
}

